VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "clsClientCAValue"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public CA_TY_M1 as Double
Public CA_TY_M2 as Double
Public CA_TY_M3 as Double
Public CA_TY_M4 as Double
Public CA_TY_M5 as Double
Public CA_TY_M6 as Double
Public CA_TY_M7 as Double
Public CA_TY_M8 as Double
Public CA_TY_M9 as Double
Public CA_TY_M10 as Double
Public CA_TY_M11 as Double
Public CA_TY_M12 as Double

Public CA_PY_M1 as Double
Public CA_PY_M2 as Double
Public CA_PY_M3 as Double
Public CA_PY_M4 as Double
Public CA_PY_M5 as Double
Public CA_PY_M6 as Double
Public CA_PY_M7 as Double
Public CA_PY_M8 as Double
Public CA_PY_M9 as Double
Public CA_PY_M10 as Double
Public CA_PY_M11 as Double
Public CA_PY_M12 as Double

Public CA_TY_YTD1 as Double
Public CA_TY_YTD2 as Double
Public CA_TY_YTD3 as Double
Public CA_TY_YTD4 as Double
Public CA_TY_YTD5 as Double
Public CA_TY_YTD6 as Double
Public CA_TY_YTD7 as Double
Public CA_TY_YTD8 as Double
Public CA_TY_YTD9 as Double
Public CA_TY_YTD10 as Double
Public CA_TY_YTD11 as Double
Public CA_TY_YTD12 as Double

Public CA_PY_YTD1 as Double
Public CA_PY_YTD2 as Double
Public CA_PY_YTD3 as Double
Public CA_PY_YTD4 as Double
Public CA_PY_YTD5 as Double
Public CA_PY_YTD6 as Double
Public CA_PY_YTD7 as Double
Public CA_PY_YTD8 as Double
Public CA_PY_YTD9 as Double
Public CA_PY_YTD10 as Double
Public CA_PY_YTD11 as Double
Public CA_PY_YTD12 as Double

Public CA_TY_Q1 as Double
Public CA_TY_Q2 as Double
Public CA_TY_Q3 as Double
Public CA_TY_Q4 as Double

Public CA_PY_Q1 as Double
Public CA_PY_Q2 as Double
Public CA_PY_Q3 as Double
Public CA_PY_Q4 as Double