VERSION 1.0 CLASS
BEGIN
  MultiUse = -1 
END
Attribute VB_Name = "clsClientInfo"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public StatYear As Integer
Public StatMonth As Integer
Public BrandName As String
Public TypeBusiness As String
Public DatabaseClientNum As Integer
Public DatabaseClientAndBrandNum As String
Public UniverseCode As Variant
Public UniversCodeAndBrand As String
Public MregName As String
Public ExtMregName As String
Public RegName As String
Public FlsmName As String
Public SecName As String
Public SrepName As String
Public ClientName As String
Public ChainName As String
Public ChainCode As Double
Public GeoCity As String
Public GeoReg As String
Public ClientTypeRus As String
Public ClientTypeEng As String
Public ClientTypeEngChort As String
Public ClientTypeEngChain As String
Public ClubStatus As String
Public EmotionStatus As String
Public CnqFullDate As Date
Public CnqYearDate As Date
Public CnqYearGA As String
Public CnqMonthNum As Integer
Public CnqMonthNameRus As String
Public CnqMonthNameEng As String
Public MagType As String
Public MagTypePrice As String
Public MagTypePlace As String
Public WorkStatusNum As Integer
Public WorkStatusName As String
Public LtmAvgCaVal As Double
Public LtmAvgCaName As String
Public LtmFrqOrders As String
Public ClientEvVal As Double
Public ClientEvName As String
Public ClientEcadCode As Variant
Public MastersEducatedAllY As Integer
Public MastersEducatedPY As Integer
Public MastersEducatedTY As Integer
Public HairdressersNum As Integer
Public HairdressersWorkPlace As Integer
Public PartnerName As String
Public PartnerCode As Variant











