VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "clsClientInfo"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public StatYear As Integer
Public StatMonth As Integer
Public BrandName As String
Public TypeBusiness As String
Public DatabaseClientNum As Integer
Public DatabaseClientAndBrandNum As String
Public UniverseCode As Variant
Public UniversCodeAndBrand As String
Public MregName As String
Public ExtMregName As String
Public RegName As String
Public FlsmName As String
Public SecName As String
Public SrepName As String
Public ClientName As String
Public ChainName As String
Public ChainNameTop As String
Public ChainCode As Double
Public GeoCity As String
Public GeoReg As String
Public ClientTypeRus As String
Public ClientTypeEng As String
Public ClientTypeEngChort As String
Public ClientTypeEngChain As String
Public ClientTypeGA As String
Public ClubStatus As String
Public EmotionStatus As String
Public CnqFullDate As Date
Public CnqYearDate As Date
Public CnqYearGA As String
Public CnqMonthNum As Integer
Public CnqMonthNameRus As String
Public CnqMonthNameEng As String
Public MagType As String
Public MagTypePrice As String
Public MagTypePlace As String
Public WorkStatusNum As Integer
Public WorkStatusName As String
Public LtmAvgCaVal As Variant
Public LtmAvgCaName As String
Public LtmFrqOrders As String
Public ClientEvVal As Double
Public ClientEvName As String
Public ClientEcadCode As Variant
Public MastersEducatedAllY As Variant
Public MastersEducatedPY As Variant
Public MastersEducatedTY As Variant
Public HairdressersNum As Integer
Public HairdressersWorkPlace As Integer
Public PartnerName As String
Public PartnerCode As Variant


Public CA_TY_M1 As Double
Public CA_TY_M2 As Double
Public CA_TY_M3 As Double
Public CA_TY_M4 As Double
Public CA_TY_M5 As Double
Public CA_TY_M6 As Double
Public CA_TY_M7 As Double
Public CA_TY_M8 As Double
Public CA_TY_M9 As Double
Public CA_TY_M10 As Double
Public CA_TY_M11 As Double
Public CA_TY_M12 As Double

Public CA_PY_M1 As Double
Public CA_PY_M2 As Double
Public CA_PY_M3 As Double
Public CA_PY_M4 As Double
Public CA_PY_M5 As Double
Public CA_PY_M6 As Double
Public CA_PY_M7 As Double
Public CA_PY_M8 As Double
Public CA_PY_M9 As Double
Public CA_PY_M10 As Double
Public CA_PY_M11 As Double
Public CA_PY_M12 As Double

Public CA_TY_YTD1 As Double
Public CA_TY_YTD2 As Double
Public CA_TY_YTD3 As Double
Public CA_TY_YTD4 As Double
Public CA_TY_YTD5 As Double
Public CA_TY_YTD6 As Double
Public CA_TY_YTD7 As Double
Public CA_TY_YTD8 As Double
Public CA_TY_YTD9 As Double
Public CA_TY_YTD10 As Double
Public CA_TY_YTD11 As Double
Public CA_TY_YTD12 As Double

Public CA_PY_YTD1 As Double
Public CA_PY_YTD2 As Double
Public CA_PY_YTD3 As Double
Public CA_PY_YTD4 As Double
Public CA_PY_YTD5 As Double
Public CA_PY_YTD6 As Double
Public CA_PY_YTD7 As Double
Public CA_PY_YTD8 As Double
Public CA_PY_YTD9 As Double
Public CA_PY_YTD10 As Double
Public CA_PY_YTD11 As Double
Public CA_PY_YTD12 As Double

Public CA_TY_Q1 As Double
Public CA_TY_Q2 As Double
Public CA_TY_Q3 As Double
Public CA_TY_Q4 As Double

Public CA_PY_Q1 As Double
Public CA_PY_Q2 As Double
Public CA_PY_Q3 As Double
Public CA_PY_Q4 As Double
